version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Bind mount
      - /app/node_modules # anonymous mount to prevent erasing node modules
    environment:
      - PORT=3000
